#ifndef FADFS_CORE_CONSTANT_H
#define FADFS_CORE_CONSTANT_H

#define FADFS_MAGIC 0x53464446
#define FADFS_VERSION 0x01
#define FADFS_BLOCK_SIZE 4096
#define FADFS_INODE_SIZE 128
#define FADFS_BLOCK_SHIFT 12
#define FADFS_FILE_AVG_SIZE 65536
#define SUPER_BLOCK_SIZE 1024

#endif //FADFS_CORE_CONSTANT_H